language: ruby
rvm:
  2.6.3

install: bundle install
#script: jekyll build && htmlproofer ./_site --disable-external
script: JEKYLL_ENV=production bundle exec jekyll build

branches:
  only:
    - jekyll-blogs # build master branch only

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache:
  bundler: true # caching bundler gem packages will speed up build
  directories:
  - vendor/bundle

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  target-branch: master
  on:
    branch: jekyll-blogs
  local-dir: _site
