# Site settings
title: PizzaBus
SEOTitle: PizzaBus
header-img: img/home-bg.jpg
email: josteinzheng@126.com
description: "stay hungry, stay foolish"
keyword: "blogs java"
url: "https://josteinzheng.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
timezone: Asia/Shanghai

# SNS settings
RSS: false
# weibo_username:     josteinzheng
# zhihu_username:     josteinzheng
github_username:    josteinzheng
#twitter_username:  josteinzheng
# facebook_username:  josteinzheng



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "vendor"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
plugins: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


#Gitalk
github_comment_repo_name: github-pages-comment
github_oauth_client_id: efc9e2f98b9fae506c3f
github_oauth_client_key: 692820da192ba1ef141ae2d425ed28c8309a5c2c

# Disqus settings
#disqus_username: _your_disqus_short_name_



# Analytics settings
# Baidu Analytics
ba_track_id: 'c7e304c71d82e4ea132118df8cb8d9e0'
# Google Analytics
# ga_track_id: 'todo'            # Format: UA-xxxxxx-xx
ga_domain: josteinzheng.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: /img/contact-bg.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "豆角",
        href: "https://zhengdouglas.github.io"
    }
]
